from .paper_analyst import PAPER_ANALYST_SYSTEM_PROMPT
from .data_acquirer import DATA_ACQUIRER_SYSTEM_PROMPT
from .data_preparer import DATA_PREPARER_SYSTEM_PROMPT
from .output_producer import OUTPUT_PRODUCER_SYSTEM_PROMPT
from .reviewer import REVIEWER_SYSTEM_PROMPT

__all__ = [
    "PAPER_ANALYST_SYSTEM_PROMPT",
    "DATA_ACQUIRER_SYSTEM_PROMPT",
    "DATA_PREPARER_SYSTEM_PROMPT",
    "OUTPUT_PRODUCER_SYSTEM_PROMPT",
    "REVIEWER_SYSTEM_PROMPT",
]
