from .paper_analyst import PAPER_ANALYST_SYSTEM_PROMPT
from .classification_mapper import CLASSIFICATION_MAPPER_SYSTEM_PROMPT
from .data_acquirer import DATA_ACQUIRER_SYSTEM_PROMPT
from .data_guide import DATA_GUIDE_SYSTEM_PROMPT
from .output_producer import (
    OUTPUT_PRODUCER_TABLES_PROMPT,
    OUTPUT_PRODUCER_FIGURES_PROMPT,
    OUTPUT_PRODUCER_FIX_PROMPT,
)
from .reviewer import REVIEWER_SYSTEM_PROMPT

__all__ = [
    "PAPER_ANALYST_SYSTEM_PROMPT",
    "CLASSIFICATION_MAPPER_SYSTEM_PROMPT",
    "DATA_ACQUIRER_SYSTEM_PROMPT",
    "DATA_GUIDE_SYSTEM_PROMPT",
    "OUTPUT_PRODUCER_TABLES_PROMPT",
    "OUTPUT_PRODUCER_FIGURES_PROMPT",
    "OUTPUT_PRODUCER_FIX_PROMPT",
    "REVIEWER_SYSTEM_PROMPT",
]
