"""
Stage 5: Output Producer

Generates all tables and figures specified in replication_spec.outputs.

Architecture: direct LLM call → execute → one fix pass (per script type).
Tables and figures are generated by separate scripts to reduce per-script complexity.
No tool-calling loop — the full context is passed upfront.

Max LLM calls: 4 (tables generate + optional fix, figures generate + optional fix).
"""
import logging
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import pandas as pd
import yaml
from rich.console import Console
from rich.panel import Panel

from agents.state import PipelineState
from agents.prompts.output_producer import (
    OUTPUT_PRODUCER_TABLES_PROMPT,
    OUTPUT_PRODUCER_FIGURES_PROMPT,
    OUTPUT_PRODUCER_FIX_PROMPT,
)

log = logging.getLogger("output_producer")
_console = Console()
MAX_FIX_ATTEMPTS = 2


def output_producer_node(state: PipelineState) -> dict:
    """Generate tables and figures via direct LLM calls (no tool loop)."""
    run_dir = Path(state["run_dir"])
    config = state.get("config", {})
    spec = state["replication_spec"]

    n_tables = len(spec["outputs"].get("tables", []))
    n_figures = len(spec["outputs"].get("figures", []))
    _console.print(Panel(
        f"[bold]Stage 5 — Output Producer[/bold]\n"
        f"Generating {n_tables} tables and {n_figures} figures",
        style="blue"
    ))

    outputs_dir = run_dir / "outputs"
    tables_dir = outputs_dir / "tables"
    figures_dir = outputs_dir / "figures"
    tables_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)

    context = _build_context(run_dir, spec)
    llm_client = _make_client(config)

    # ── Tables ────────────────────────────────────────────────────────────────
    if n_tables:
        tables_spec = yaml.dump(
            {"tables": spec["outputs"]["tables"]}, default_flow_style=False
        )
        tables_msg = _user_message_tables(context, tables_spec, tables_dir)
        ok = _run_script_with_fix(
            llm_client, config, OUTPUT_PRODUCER_TABLES_PROMPT,
            tables_msg, run_dir, "generate_tables",
        )
        if not ok:
            raise RuntimeError(
                "Table generation failed after fix attempt — reviewer would see 0 outputs. "
                "Check generated_scripts/generate_tables*.py and its stderr for details."
            )

    # ── Figures ───────────────────────────────────────────────────────────────
    if n_figures:
        figures_spec = yaml.dump(
            {"figures": spec["outputs"]["figures"]}, default_flow_style=False
        )
        figures_msg = _user_message_figures(context, figures_spec, figures_dir)
        ok = _run_script_with_fix(
            llm_client, config, OUTPUT_PRODUCER_FIGURES_PROMPT,
            figures_msg, run_dir, "generate_figures",
        )
        if not ok:
            raise RuntimeError(
                "Figure generation failed after fix attempt — reviewer would see 0 outputs. "
                "Check generated_scripts/generate_figures*.py and its stderr for details."
            )

    # ── Collect output paths ───────────────────────────────────────────────────
    output_paths: dict[str, str] = {}
    for table in spec["outputs"].get("tables", []):
        tid = table["id"]
        for ext in ("csv", "xlsx"):
            p = tables_dir / f"{tid}.{ext}"
            if p.exists():
                output_paths[f"{tid}_{ext}" if ext != "csv" else tid] = str(p)

    for figure in spec["outputs"].get("figures", []):
        fid = figure["id"]
        for ext in ("png", "pdf"):
            p = figures_dir / f"{fid}.{ext}"
            if p.exists():
                output_paths[f"{fid}_{ext}" if ext != "png" else fid] = str(p)

    produced = len(output_paths)
    expected = n_tables * 2 + n_figures * 2
    _console.print(
        f"  [{'green' if produced >= expected else 'yellow'}]"
        f"{'✓' if produced >= expected else '⚠'}[/] "
        f"{produced}/{expected} output files produced"
    )
    log.info(f"Output paths: {list(output_paths.keys())}")
    return {"output_paths": output_paths, "current_stage": 5}


# ---------------------------------------------------------------------------
# Context builder
# ---------------------------------------------------------------------------

def _build_context(run_dir: Path, spec: dict) -> str:
    """Build the full data context string passed to both table and figure generators."""
    decomp_dir = run_dir / "data" / "decomposition"
    lines = ["## Available data files\n"]

    if decomp_dir.exists():
        for csv_path in sorted(decomp_dir.glob("*.csv")):
            try:
                df = pd.read_csv(csv_path, nrows=5)
                lines.append(f"### {csv_path}  (absolute path)")
                lines.append(f"columns: {list(df.columns)}")
                lines.append(df.to_string(index=False, max_cols=10))
                lines.append("")
            except Exception as e:
                lines.append(f"### {csv_path}  (could not read: {e})\n")

    # Also load data_guide alignment notes if available
    guide_path = run_dir / "data" / "raw" / "data_guide.yaml"
    if guide_path.exists():
        try:
            guide = yaml.safe_load(guide_path.read_text()) or {}
            notes = guide.get("alignment", {}).get("notes", [])
            if notes:
                lines.append("## Data guide alignment notes")
                for note in notes:
                    lines.append(f"- {note}")
                lines.append("")
        except Exception:
            pass

    geo = spec.get("geography", {})
    country_codes = [e["code"] for e in geo.get("analysis_entities", [])]
    lines.append(f"## Country codes in data\n{country_codes}\n")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# User message builders
# ---------------------------------------------------------------------------

def _user_message_tables(context: str, tables_spec: str, tables_dir: Path) -> str:
    return f"""{context}

## Tables to generate
```yaml
{tables_spec}
```

## Output directory (absolute)
{tables_dir}

Save each table as `<id>.csv` and `<id>.xlsx` in the output directory above.
Use the EXACT absolute paths from "Available data files" when reading input CSVs.
Write the complete Python script now.
"""


def _user_message_figures(context: str, figures_spec: str, figures_dir: Path) -> str:
    return f"""{context}

## Figures to generate
```yaml
{figures_spec}
```

## Output directory (absolute)
{figures_dir}

Save each figure as `<id>.png` (dpi=150) and `<id>.pdf` in the output directory above.
Use the EXACT absolute paths from "Available data files" when reading input CSVs.
Write the complete Python script now.
"""


# ---------------------------------------------------------------------------
# LLM call + execute + fix
# ---------------------------------------------------------------------------

def _run_script_with_fix(
    client,
    config: dict,
    system_prompt: str,
    user_message: str,
    run_dir: Path,
    script_name: str,
) -> bool:
    """Generate a script, execute it. On failure, ask the LLM to fix once."""
    model = _resolve_model(config, "output_producer")
    max_tokens = config.get("llm", {}).get("output_producer_max_tokens", 8000)

    # Generate
    _console.print(f"  [dim]Generating {script_name}...[/dim]")
    script = _call_llm(client, model, max_tokens, system_prompt, user_message)
    script = _strip_fences(script)

    success, stderr = _execute(script, run_dir, script_name)
    if success:
        _console.print(f"  [green]✓[/green] {script_name}")
        return True

    # One fix attempt
    _console.print(f"  [yellow]⚠[/yellow] {script_name} failed — fixing...")
    log.warning(f"{script_name} error:\n{stderr[:500]}")

    fix_message = (
        f"Error:\n```\n{stderr[:1500]}\n```\n\n"
        f"Original script:\n```python\n{script}\n```"
    )
    fixed_script = _call_llm(
        client, model, max_tokens, OUTPUT_PRODUCER_FIX_PROMPT, fix_message
    )
    fixed_script = _strip_fences(fixed_script)

    success, stderr2 = _execute(fixed_script, run_dir, f"{script_name}_fixed")
    if success:
        _console.print(f"  [green]✓[/green] {script_name} (fixed)")
        return True

    _console.print(f"  [red]✗[/red] {script_name} still failing after fix")
    log.error(f"{script_name} fix failed:\n{stderr2[:500]}")
    return False


def _call_llm(client, model: str, max_tokens: int, system: str, user: str) -> str:
    """Single Anthropic API call (streaming for large outputs)."""
    params = dict(
        model=model,
        max_tokens=max_tokens,
        system=system,
        messages=[{"role": "user", "content": user}],
    )
    with client.messages.stream(**params) as stream:
        response = stream.get_final_message()
    usage = response.usage
    log.info(
        f"output_producer LLM: {usage.input_tokens} in + {usage.output_tokens} out tokens "
        f"(~${(usage.input_tokens * 3 + usage.output_tokens * 15) / 1_000_000:.4f})"
    )
    return response.content[0].text.strip()


# Modules that generated scripts should never import
_FORBIDDEN_IMPORTS = frozenset({"subprocess", "socket", "urllib", "requests", "shutil"})


def _check_script_safety(script: str) -> None:
    """Raise ValueError if the script imports a forbidden module."""
    for mod in _FORBIDDEN_IMPORTS:
        if re.search(rf"\bimport\s+{mod}\b", script) or re.search(rf"\bfrom\s+{mod}\b", script):
            raise ValueError(
                f"Generated script imports forbidden module '{mod}'. "
                "Regeneration required."
            )


def _execute(script: str, run_dir: Path, name: str) -> tuple[bool, str]:
    """Write script to generated_scripts/ and execute it."""
    try:
        _check_script_safety(script)
    except ValueError as e:
        log.error(f"Script safety check failed for {name}: {e}")
        return False, str(e)

    scripts_dir = run_dir / "generated_scripts"
    scripts_dir.mkdir(exist_ok=True)
    script_path = scripts_dir / f"{name}.py"
    script_path.write_text(script)

    result = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=str(run_dir),
        capture_output=True,
        text=True,
        timeout=120,
    )
    if result.returncode == 0:
        return True, ""
    return False, (result.stderr or result.stdout)[-2000:]


def _strip_fences(text: str) -> str:
    text = re.sub(r"^```python\s*\n", "", text, flags=re.IGNORECASE)
    text = re.sub(r"^```\s*\n", "", text, flags=re.MULTILINE)
    text = re.sub(r"\n```\s*$", "", text)
    return text.strip()


# ---------------------------------------------------------------------------
# LLM client
# ---------------------------------------------------------------------------

def _make_client(config: dict):
    import anthropic
    providers = config.get("llm", {}).get("providers", {})
    key_env = providers.get("anthropic", {}).get("api_key_env", "ANTHROPIC_API_KEY")
    api_key = os.environ.get(key_env)
    if not api_key:
        raise EnvironmentError(f"{key_env} not set")
    return anthropic.Anthropic(api_key=api_key)


def _resolve_model(config: dict, agent: str) -> str:
    routing = config.get("llm", {}).get("routing", {})
    model_str = routing.get(agent, "claude-sonnet-4-6")
    return model_str.split("/", 1)[1] if "/" in model_str else model_str
